#ifndef _IN18CLOCK_USER_SETUP_H_
#define _IN18CLOCK_USER_SETUP_H_

void doTest();

#define MENU_EDIT_TIME_FORMAT	3
#define MENU_EDIT_HOURS		4
#define MENU_EDIT_MINUTES	5
#define MENU_EDIT_SECONDS	6
#define MENU_EDIT_DATE_FORMAT	7
#define MENU_EDIT_DAY		8
#define MENU_EDIT_MONTH		9
#define MENU_EDIT_YEAR		10
#define MENU_EDIT_TEMP_UNIT	11

#endif //_IN18CLOCK_USER_SETUP_H_
